workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      
      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator --debug
      
      - name: Package simulator app
        script: |
          cd build/ios/iphonesimulator
          zip -r simulator-app.zip Runner.app
    
    artifacts:
      - build/ios/iphonesimulator/simulator-app.zip
    
    publishing:
      email:
        recipients:
          - hanklee0606@gmail.com

  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    
    environment:
      flutter: stable
    
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      
      - name: Build Android APK
        script: flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - hanklee0606@gmail.com